service: kaist-food-bot

package:
  exclude:
    - node_modules/**
    - .vscode/**
    - venv/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

custom:
  env: ${file(./serverless.env.yml):${self:provider.stage}}
  pythonRequirements:
    noDeploy:
      - autopep8
      - pipdeptree
      - pylint

provider:
  name: aws
  runtime: python3.6
  profile: overscoreServerless
  region: ap-northeast-2
  stage: ${opt:stage, 'development'}
  environment:
    TELEGRAM_TOKEN: ${self:custom.env.TELEGRAM_TOKEN}
    TZ: ${self:custom.env.TZ}
    CHATS_DYNAMODB_TABLE: ${self:service}-chats-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHATS_DYNAMODB_TABLE}"

functions:
  webhook:
    handler: src/handlers/webhook.webhook
    events:
      - http: POST /
    warmup:
      enabled: true
  set_webhook:
    handler: src/handlers/webhook.set_webhook
    events:
      - http: POST /set_webhook
  deliver:
    handler: src/handlers/deliver.deliver
    events:
      - schedule: ${self:custom.env.CRON_SCHEDULE}

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup

